spring.application.name=validation-service
spring.datasource.url=jdbc:postgresql://localhost:5433/validation_db
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=
server.ssl.key-store-type=PKCS12


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
